[package]
name = "taskmaster-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.8", features=["derive"]}
serde = "1.0.203"
serde_derive = "1.0.203"
serde_yml = "0.0.10"
rustyline = "14.0.0"